/*
 * Microsoft 365 App
 *
 * API to access and configure the Microsoft 365 App
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

// GetDashboardTemplateByName200Response - A frontend dashboard
type GetDashboardTemplateByName200Response struct {

	// The internal Id of dashboard
	Id int32 `json:"id,omitempty"`

	// The name for this dashboard
	Name string `json:"name"`

	// ID of the project to which the dashboard belongs
	ProjectId string `json:"projectId"`

	// ID of the user who owns the dashboard
	UserId string `json:"userId"`

	// The sequence of the dashboard
	Sequence int32 `json:"sequence,omitempty"`

	Widgets []GetDashboardTemplateByName200ResponseWidgetsInner `json:"widgets,omitempty"`
}

// AssertGetDashboardTemplateByName200ResponseRequired checks if the required fields are not zero-ed
func AssertGetDashboardTemplateByName200ResponseRequired(obj GetDashboardTemplateByName200Response) error {
	elements := map[string]interface{}{
		"name":      obj.Name,
		"projectId": obj.ProjectId,
		"userId":    obj.UserId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	for _, el := range obj.Widgets {
		if err := AssertGetDashboardTemplateByName200ResponseWidgetsInnerRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertGetDashboardTemplateByName200ResponseConstraints checks if the values respects the defined constraints
func AssertGetDashboardTemplateByName200ResponseConstraints(obj GetDashboardTemplateByName200Response) error {
	return nil
}
