/*
 * Microsoft 365 App
 *
 * API to access and configure the Microsoft 365 App
 *
 * API version: 1.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

type ProxyResponseInner struct {
	ConfigId int32 `json:"config_id,omitempty"`

	Username string `json:"username,omitempty"`

	Code int32 `json:"code,omitempty"`

	Body map[string]interface{} `json:"body,omitempty"`
}

// AssertProxyResponseInnerRequired checks if the required fields are not zero-ed
func AssertProxyResponseInnerRequired(obj ProxyResponseInner) error {
	return nil
}

// AssertProxyResponseInnerConstraints checks if the values respects the defined constraints
func AssertProxyResponseInnerConstraints(obj ProxyResponseInner) error {
	return nil
}
