/*
 * Microsoft 365 App
 *
 * API to access and configure the Microsoft 365 App
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

type ProxyResponseInner struct {
	ConfigId int32 `json:"config_id,omitempty"`

	Username string `json:"username,omitempty"`

	Code int32 `json:"code,omitempty"`

	Body map[string]interface{} `json:"body,omitempty"`
}

// AssertProxyResponseInnerRequired checks if the required fields are not zero-ed
func AssertProxyResponseInnerRequired(obj ProxyResponseInner) error {
	return nil
}

// AssertRecurseProxyResponseInnerRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of ProxyResponseInner (e.g. [][]ProxyResponseInner), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseProxyResponseInnerRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aProxyResponseInner, ok := obj.(ProxyResponseInner)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertProxyResponseInnerRequired(aProxyResponseInner)
	})
}
