/*
 * Microsoft 365 App
 *
 * API to access and configure the Microsoft 365 App
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

// GetDashboardTemplateByName200ResponseWidgetsInnerDataInner - Data for a widget
type GetDashboardTemplateByName200ResponseWidgetsInnerDataInner struct {

	// The internal Id of widget data
	Id int32 `json:"id,omitempty"`

	// Position of the element in widget type
	ElementSequence int32 `json:"elementSequence,omitempty"`

	// The master asset id of this widget
	AssetId int32 `json:"assetId,omitempty"`

	// individual config parameters depending on category
	Data map[string]interface{} `json:"data,omitempty"`
}

// AssertGetDashboardTemplateByName200ResponseWidgetsInnerDataInnerRequired checks if the required fields are not zero-ed
func AssertGetDashboardTemplateByName200ResponseWidgetsInnerDataInnerRequired(obj GetDashboardTemplateByName200ResponseWidgetsInnerDataInner) error {
	return nil
}

// AssertGetDashboardTemplateByName200ResponseWidgetsInnerDataInnerConstraints checks if the values respects the defined constraints
func AssertGetDashboardTemplateByName200ResponseWidgetsInnerDataInnerConstraints(obj GetDashboardTemplateByName200ResponseWidgetsInnerDataInner) error {
	return nil
}
