/*
 * Microsoft 365 App
 *
 * API to access and configure the Microsoft 365 App
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apiserver

import (
	"time"
)

type CreateBookingRequest struct {

	// The ID of the asset which is being booked.
	AssetId string `json:"assetId,omitempty"`

	// The start datetime of the booking in ISO 8601 format.
	Start time.Time `json:"start"`

	// The end datetime of the booking in ISO 8601 format.
	End time.Time `json:"end"`

	// Email address of the organizer or attendee.
	Email string `json:"email"`

	// Password for authentication or verification.
	Password string `json:"password"`

	// The name of the event. (Optional)
	EventName string `json:"eventName,omitempty"`

	// A description of the event or booking. (Optional)
	Description string `json:"description,omitempty"`
}

// AssertCreateBookingRequestRequired checks if the required fields are not zero-ed
func AssertCreateBookingRequestRequired(obj CreateBookingRequest) error {
	elements := map[string]interface{}{
		"start":    obj.Start,
		"end":      obj.End,
		"email":    obj.Email,
		"password": obj.Password,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertCreateBookingRequestConstraints checks if the values respects the defined constraints
func AssertCreateBookingRequestConstraints(obj CreateBookingRequest) error {
	return nil
}
